<div class="extra-central">
    <div class="container">
        <div class="row">
            <div class="col-xs-5 bloco-solucoes">

                <div class="col-xs-7 box-chamada">
                   <ul class="cycle-slideshow" data-cycle-fx="" data-cycle-timeout="5000" data-cycle-speed="1800" data-cycle-slides="> li" data-cycle-easing="easeInOutExpo" data-cycle-log="false">
                        <? foreach ($this->voDestaque as $oDestaque) { ?>
                            <li>
                                <p class="media-heading"><?=$oDestaque->TITULO;?></p>
                                <div class="col-xs-5">
                                    <!-- TODO mudar para link -->
                                    <button class="btn">SAIBA MAIS</button>
                                </div>
                            </li>
                        <? } ?>
                        <div class="cycle-pager"></div>
                    </ul>
                </div>
                <div class="col-xs-12 nossas-obras">
                    <p>NOSSAS OBRAS</p>
                </div>
            </div>
            <div class="col-xs-3"></div>
            <div class="col-xs-4 informacoes-contato">
                    <div class="telefone">
                        <p class="title-telefone"><strong>NOSSO TELEFONE</strong><br/>91.32230322</p>
                    </div>
                    <div class="onde-fica">
                        <a href="/contato">ONDE<br/><strong>FICA?</strong></a>
                    </div>
             </div>
            <?=$this->partial('/_includes/obras.phtml', array('voObra' => $this->voObra));?>
        </div>
    </div>
    <?=$this->partial('/_includes/dicas.phtml', array('voDica' => $this->voDica));?>
</div>