<div id="CONTATO" class="container">
    <div class="row">
        <div class="col-xs-7">
            <p class="chamada">Envie sua mensagem. <br/>Será um prazer lhe atender</p>
            <form action="#" method="post" id="FRM-CONTATO">
                <div class="form-group">
                    <input type="text" class="validate[required]" name="NOME" id="NOME" placeholder="Nome">
                </div>
                <div class="form-group">
                    <input type="text" class="validate[required]" name="EMAIL" id="EMAIL" placeholder="E-mail">
                </div>
                <div class="form-group">
                    <input type="text" class="validate[required]" name="ASSUNTO" id="ASSUNTO" placeholder="Assunto">
                </div>
                <div class="form-group">
                    <textarea name="MENSAGEM" id="MENSAGEM" placeholder="Deixe seu comentário aqui"></textarea>
                </div>
                <div class="form-group">
                    <div class="col-xs-8">
                        <p class="obs">Nosso serviço de atendimento funciona das 9 às 17 horas, de segunda a sexta, exceto feriados.</p>
                    </div>
                    <div class="col-xs-4">
                        <button class="btn btn-default">Enviar</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-xs-5">
            <div class="bloco-central">
                <p class="black">HORÁRIO DE FUNCIONAMENTO</p>
                <p class="light">7:30 as 12:00 - 13:00 as 17:30 (seg. a qui.)</p>
                    <p class="light">7:30 as 12:00 - 13:00 as 16:30 (às sextas)</p>
            </div>
            <div class="bloco-central">
                <img src="/imagem/site/icon-telefone.jpg" class="pull-left"/><p class="black">TELEFONE</p>
                <p class="light">91.3223-0322</p>
            </div>
            <div class="bloco-central">
                <p class="black">
                    ENDEREÇO
                </p>
                <p class="light">
                    Rua Curuçá, 734
                    Bairro: TELEGRAFO SEM FIO
                    Cidade: Belém; CEP 66.050-080
                </p>
            </div>
            <img src="/imagem/site/atendente-contato.jpg"/>
        </div>
        <?=$this->partial('/_includes/obras.phtml', array('voObra' => $this->voObra));?>
    </div>
</div>
<?=$this->partial('/_includes/parceiros.phtml', array('voParceiro' => $this->voParceiro));?>