<div id="INSTITUCIONAL" class="pagina_detalhe">
	<div class="page-header">
		<div class="container">
			<h1><?=$this->oPagina->TITULO;?></h1>
		</div> <!-- .container -->
	</div> <!-- .page-header -->
	<div class="container">
		<div class="text_format historia-content">
			<div class="row line-1">
				<div class="col-xs-6 col-xs-offset-1">
					<span class="box-imagem imagem-bottom">
						<span class="legenda">
							O começo de tudo: experimentações com combinação de cachaça com ervas e frutas.
						</span>
						<span class="imagem"><img src="/imagem/site/historia-01.jpg" alt="" width="278"></span>
					</span>
				</div>
			</div> <!-- .row -->
			<div class="row line-2">
				<div class="col-xs-4 left">
					<span class="box-imagem imagem-bottom">
						<span class="imagem"><img src="/imagem/site/garrafa-3.jpg" alt="" width="208"></span>
					</span>
				</div> <!-- .col-xs-4 -->
				<div class="col-xs-5 mid">
					<?=$this->oPagina->TEXTO;?>
				</div> <!-- .col-xs-5 -->
				<div class="col-xs-3 right">
					<div class="row">
						<div class="col-xs-6">
							<br>
							<br>
							<span class="box-imagem imagem-bottom">
								<span class="imagem"><img src="/imagem/site/garrafa-1.jpg" alt="" width="82"></span>
							</span>
						</div>
						<div class="col-xs-6">
							<span class="box-imagem imagem-bottom">
								<span class="imagem"><img src="/imagem/site/garrafa-2.jpg" alt="" width="92"></span>
								<span class="legenda">
									Recordar é viver: rótulos clássico da Cachaça de Jambu.
								</span>
							</span>
						</div>
					</div>
				</div> <!-- .col-xs-3 -->
			</div>
		</div>
	</div> <!-- .container -->
</div>
