<div id="LOJA" class="pagina_detalhe">
	<div class="page-header">
		<div class="container">
			<h1><?= $this->oPagina->TITULO;?></h1>
			<a href="#" class="ribbon">
				<span class="line-1">Frete grátis Brasil</span>
				<span class="line-2">consulte condições</span>
			</a>
		</div> <!-- .container -->
	</div> <!-- .page-header -->
	<div class="container">
		<div class="text_format"><?= $this->oPagina->TEXTO ?></div>
		<ul class="vitrine clearfix">
            <? foreach ($this->voProduto as $oProduto) { ?>
                <? if ($oProduto->ID_CATEGORIA == RowProProduto::PRODUTO) { ?>
                    <li class="produto">
                        <div class="content">
                            <div class="imagem">
                                <a href="/produto/<?=$oProduto->PERMALINK;?>" title="Saiba mais">
                                    <img src="<?=$oProduto->linkImagemDestaque();?>" alt="<?=$oProduto->NOME;?>">
                                </a>
                            </div>
                            <div class="text">
                                <p class="title"><?=$oProduto->ETIQUETA;?></p>
                            </div>
                            <div class="button">
                                <a href="/produto/<?=$oProduto->PERMALINK;?>" class="btn btn-primary btn-comprar" title="Saiba mais">Ver detalhes</a>
                            </div> <!-- .button -->
                        </div> <!-- .content -->
                    </li>
                <? }elseif ($oProduto->ID_CATEGORIA == RowProProduto::PRODUTO_DESTAQUE) { ?>
                    <li class="produto big">
                        <div class="content">
                            <div class="imagem">
                                <a href="/produto/<?=$oProduto->PERMALINK;?>" title="Saiba mais">
                                    <img src="<?=$oProduto->linkImagemDestaque();?>" alt="<?=$oProduto->NOME;?>">
                                </a>
                            </div>
                            <div class="button">
                                <a href="/produto/<?=$oProduto->PERMALINK;?>" class="btn btn-primary btn-comprar" title="Saiba mais">Ver detalhes</a>
                            </div> <!-- .button -->
                        </div> <!-- .content -->
                    </li>
                <? } ?>
            <? } ?>
		</ul>
		<div class="row">
			<div class="col-xs-5 text-center">
				<p>
					<img src="/imagem/site/cachaca-jambu.png" alt="Logo Cachaça de Jambú">
				</p>
				<p>
					Só a original Cachaça de Jambu proporciona uma experiência intensa que combina a magia do Jambu da Amazônia e o sabor exclusivo da cachaça artesanal em uma mistura anestésicas e afrodisíacas (700ml ou 275ml). Para comprar mais de uma unidade escolha a combinação abaixo.
				</p>
			</div> <!-- .col-xs-5 -->
			<div class="col-xs-2 text-center">
				
			</div> <!-- .col-xs-2 -->
			<div class="col-xs-5 text-center">
				<p>
					<img src="/imagem/site/jambucy.png" alt="Logo Jambucy">
				</p>
				<p>
					Prepare-se para desvendar os mistérios da Amazônia viajando entre sensações e sabores exóticos da Jambucy. Delicioso licor preparado com Cachaça de Jambu e  frutos selvagens da floresta nos sabores Açai, Castanha, Cupuaçu, Bacuri e Menta (275ml). Para comprar mais de uma unidade escolha a combinação abaixo.
				</p>
			</div> <!-- .col-xs-5 -->
		</div> <!-- .row -->
		<hr>
        <?= $this->partial('/_includes/inc_ofertas.phtml', array('voProduto' => $this->voProdutoCombinacao)); ?>
	</div> <!-- .container -->
</div>
