<?php 
// METATAGS OPEN GRAPH START
$this->headMeta()->appendName('og:image', "http://" . $_SERVER['SERVER_NAME'] .$this->oPagina->linkImagemDestaque()); 
$this->headMeta()->appendName('og:title',strip_tags($this->oPagina->TITULO.' - '.Zend_Registry::get("oConfiguracao")->TITULO)); 
if ($this->oPagina->RESUMO) {
	$this->headMeta()->appendName('og:description',strip_tags($this->oPagina->RESUMO)); 
} else {
	$this->headMeta()->appendName('og:description',strip_tags($this->oPagina->TEXTO)); 
} //if ($this->oPagina->RESUMO) {
// METATAGS OPEN GRAPH END
	?>
	<? $url = "http://" . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI']; ?>
	<div id="NOTICIA_DETALHE" class="pagina_detalhe">
		<div class="page-header">
			<div class="container">
				<h1><a href="/novidades/">Novidades</a></h1>
			</div> <!-- .container -->
		</div> <!-- .page-header -->
		<div class="container">
			<span class="pull-right box-imagem">
				<span class="imagem"><?= $this->oPagina->getImgDestaque(array(400,400)) ?></span>
			</span>
			<span><?= $this->oPagina->getDataF() ?></span>
			<h2 class="text-success"><?= $this->oPagina->TITULO ?></h2>
			<div class="box-share">
				<!-- ################# GPLUS START ##################### -->
				<div class="share-gplus">

					<div class="g-plusone" data-size="medium" data-href="<?= $url ?>"></div>

					<script type="text/javascript">
					window.___gcfg = {lang: 'pt-BR'};

					(function() {
						var po = document.createElement('script');
						po.type = 'text/javascript';
						po.async = true;
						po.src = 'https://apis.google.com/js/plusone.js';
						var s = document.getElementsByTagName('script')[0];
						s.parentNode.insertBefore(po, s);
					})();
					</script>
				</div>
				<!-- ################# GPLUS END ##################### -->
				<!--################# TWITTER START ##################### -->
				<div class="share-twitter">
					<a href="https://twitter.com/share" class="twitter-share-button" data-lang="pt" data-url="<?= $url ?>">Tweetar</a>
					<script>!function(d, s, id) {
						var js, fjs = d.getElementsByTagName(s)[0];
						if (!d.getElementById(id)) {
							js = d.createElement(s);
							js.id = id;
							js.src = "//platform.twitter.com/widgets.js";
							fjs.parentNode.insertBefore(js, fjs);
						}
					}(document, "script", "twitter-wjs");</script>
				</div>
				<!-- ################# TWITTER END ##################### -->
				<!-- ################# FACEBOOK END ##################### -->
				<div class="share-facebook">
					<div id="fb-root"></div>
					<script>(function(d, s, id) {
						var js, fjs = d.getElementsByTagName(s)[0];
						if (d.getElementById(id)) return;
						js = d.createElement(s); js.id = id;
						js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&appId=607367415995227&version=v2.0";
						fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));</script>
					<div class="fb-like" data-href="<?= $url ?>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
				</div>
				<!-- ################# FACEBOOK END ##################### -->
			</div> <!-- .box-share -->
			<div class="text_format"><?= $this->oPagina->TEXTO ?></div>
		</div>
	</div>
	<?// $this->partial('_includes/inc_comentario.phtml',array('ID_PAGINA'=>$this->oPagina->ID));?>
