<script>
    $(function(){
        $('.obras-mask').on('mouseover', function(){
            $(this).find('.mascara').stop().fadeIn();
        });

        $('.obras-mask').on('mouseout', function(){
            $(this).find('.mascara').stop().fadeOut();
        });

        openModal();
    });
</script>
<div id="OBRAS" class="container">
    <p class="titulo-obras"><?=$this->oPagina->TITULO;?></p>
    <div class="empreendimentos">
        <div class="row">
            <? foreach ($this->voObra as $oObra) { ?>
                <div class="col-xs-6">
                    <div class="obra">
                        <a href="#<?=$oObra->PERMALINK;?>" class="obras-mask" data-toggle="modal">
                        <span class="mascara">
                            <p class="tipo"><?=$oObra->RESUMO;?></p>
                            <p class="title"><?=$oObra->TITULO;?></p>
                            <img class="visualizar" src="/imagem/site/lupa.png"/>
                        </span>
                            <?=$oObra->getImgDestaque(array(469, 323));?>
                        </a>
                    </div>
                </div>
            <? } ?>
        </div>
    </div>
</div>
<?=$this->partial('/_includes/parceiros.phtml', array('voParceiro' => $this->voParceiro));?>
<? foreach ($this->voObra as $oObra) { ?>
    <div class="modal fade modal-projetos" id="<?=$oObra->PERMALINK;?>">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="row">
                        <div class="col-xs-12">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="paginator">

                            </div>
                        </div>
                        <div class="col-xs-7 texto">
                            <span class="tipo"><?=$oObra->RESUMO;?></span>
                            <h2 class="modal-title"><?=$oObra->TITULO;?></h2>

                            <div class="text-left">
                                <p><?=$oObra->TEXTO;?></p>
                            </div>
                        </div>
                    </div>

                </div> <!-- .modal-header -->
                <div class="modal-body">
                    <div class="page-projeto">

                        <div id="slideshow-1">
                            <ul id="cycle-1" class="cycle-slideshow" data-cycle-slides="> li" data-cycle-timeout="0" data-cycle-prev="#<?=$oObra->PERMALINK;?> #slideshow-1 .cycle-prev" data-cycle-next="#<?=$oObra->PERMALINK;?> #slideshow-1 .cycle-next" data-cycle-caption="#<?=$oObra->PERMALINK;?> #slideshow-1 .custom-caption" data-cycle-caption-template="Slide {{slideNum}} of {{slideCount}}" data-cycle-fx="tileBlind">
                                <? $oArquivo = $oObra->getArquivoDestaque();
                                $voArquivo = $oObra->getArquivo();
                                ?>
                                <? foreach ($voArquivo as $oArquivo) { ?>
                                    <li>
                                        <div class="content">
                                            <?= $oArquivo->renderImagem(array(939, 617)); ?>
                                        </div>
                                    </li>
                                <? } ?>
                            </ul> <!-- #cycle-1 -->
                        </div> <!-- #<?//= $oPagina->PERMALINK; ?> #slideshow-1 -->
                        <div id="slideshow-2">
                            <ul id="cycle-2" class="cycle-slideshow cycle-obras" data-cycle-slides="> li" data-cycle-timeout="0" data-cycle-prev="#<?=$oObra->PERMALINK;?> #slideshow-2 .cycle-prev" data-cycle-next="#<?=$oObra->PERMALINK;?> #slideshow-2 .cycle-next" data-cycle-caption="#<?=$oObra->PERMALINK;?> #slideshow-2 .custom-caption" data-cycle-caption-template="Slide {{slideNum}} of {{slideCount}}" data-cycle-fx="carousel" data-cycle-carousel-visible="5" data-allow-wrap="false">
                                <? foreach ($voArquivo as $oArquivo) { ?>
                                    <li>
                                        <a href="javascript:void(0);" class="link-imagem">
                                            <?= $oArquivo->renderImagem(array(187, 115)); ?>
                                        </a>
                                    </li>
                                <? } ?>
                            </ul> <!-- #cycle-2 -->
                            <a href="javascript:void(0);" class="cycle-prev"><span class="icon-arrow-left-white"></span></a>
                            <a href="javascript:void(0);" class="cycle-next"><span class="icon-arrow-right-white"></span></a>
                        </div> <!-- # #slideshow-2 -->
                    </div> <!-- .page-projeto -->
                </div> <!-- .modal-body -->
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <script>
        jQuery(document).ready(function($) {

            var slideshows = $('#<?=$oObra->PERMALINK;?> .cycle-slideshow').on('cycle-next cycle-prev', function(e, opts) {
                // advance the other slideshow
                slideshows.not(this).cycle('goto', opts.currSlide);
            });

            $('#<?=$oObra->PERMALINK;?> #cycle-2 .cycle-slide').click(function() {
                var index = $('#<?=$oObra->PERMALINK;?> #cycle-2').data('cycle.API').getSlideIndex(this);
                slideshows.cycle('goto', index);
            });

            $(".modal-content").css('border', 'none');
        });
    </script>
<? } ?>