<div id="OBRAS" class="container">
    <p class="titulo-obras">This is Photoshop version of lorem ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudir, lorem quis.</p>
    <div class="empreendimentos">
        <div class="row">
            <div class="col-xs-6">
                <div class="obra">
                    <a href="">
                        <img src="/imagem/site/obra-1.jpg"/>
                    </a>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="obra">
                    <a href="">
                        <img src="/imagem/site/obra-2.jpg"/>
                    </a>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="obra">
                    <a href="">
                        <img src="/imagem/site/obra-1.jpg"/>
                    </a>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="obra">
                    <a href="">
                        <img src="/imagem/site/obra-2.jpg"/>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<?=$this->partial('/_includes/parceiros.phtml');?>