<script>
    $(function(){
        $('.obras-mask').on('mouseover', function(){
           $(this).find('.mascara').stop().fadeIn();
        });

        $('.obras-mask').on('mouseout', function(){
            $(this).find('.mascara').stop().fadeOut();
        });

        openModal();
    });
</script>
<div id="OBRAS" class="container">
    <p class="titulo-obras">This is Photoshop version of lorem ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudir, lorem quis.</p>
    <div class="empreendimentos">
        <div class="row">
            <div class="col-xs-6">
                <div class="obra">

                    <a href="#teste1" class="obras-mask" data-toggle="modal">
                        <span class="mascara">
                            <p class="tipo">Projetos Corporativos</p>
                            <p class="title">Projetos Comerciais</p>
                            <img class="visualizar" src="/imagem/site/lupa.png"/>
                        </span>
                        <img src="/imagem/site/obra-1.jpg"/>
                    </a>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="obra">
                    <a href="" class="obras-mask">
                        <span class="mascara">
                            <p class="tipo">Projetos Corporativos</p>
                            <p class="title">Projetos Comerciais</p>
                            <img class="visualizar" src="/imagem/site/lupa.png"/>
                        </span>
                        <img src="/imagem/site/obra-2.jpg"/>
                    </a>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="obra">
                    <a href="" class="obras-mask">
                        <span class="mascara">
                            <p class="tipo">Projetos Corporativos</p>
                            <p class="title">Projetos Comerciais</p>
                            <img class="visualizar" src="/imagem/site/lupa.png"/>
                        </span>
                        <img src="/imagem/site/obra-1.jpg"/>
                    </a>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="obra">
                    <a href="" class="obras-mask">
                        <span class="mascara">
                            <p class="tipo">Projetos Corporativos</p>
                            <p class="title">Projetos Comerciais</p>
                            <img class="visualizar" src="/imagem/site/lupa.png"/>
                        </span>
                        <img src="/imagem/site/obra-2.jpg"/>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<?=$this->partial('/_includes/parceiros.phtml');?>
<div class="modal fade modal-projetos" id="teste1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <div class="row">
                    <div class="col-xs-12">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-5">
                        <div class="paginator">

                        </div>
                    </div>
                    <div class="col-xs-7 texto">
                        <span class="tipo">Residencial</span>
                        <h2 class="modal-title">Prédio Condominial Familiar</h2>

                        <div class="text-left">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum finibus sollicitudin lacinia. Fusce vestibulum hendrerit erat eget fermentum.</p>
                        </div>
                    </div>
                </div>

            </div> <!-- .modal-header -->
            <div class="modal-body">
                <div class="page-projeto">

                    <div id="slideshow-1">
                        <ul id="cycle-1" class="cycle-slideshow" data-cycle-slides="> li" data-cycle-timeout="0" data-cycle-prev="#teste1 #slideshow-1 .cycle-prev" data-cycle-next="#teste1 #slideshow-1 .cycle-next" data-cycle-caption="#teste1 #slideshow-1 .custom-caption" data-cycle-caption-template="Slide {{slideNum}} of {{slideCount}}" data-cycle-fx="tileBlind">
                                <li>
                                    <div class="content">
                                        <img src="/imagem/site/obra-big.jpg"/>

                                    </div>
                                </li>

                        </ul> <!-- #cycle-1 -->
                    </div> <!-- #<?//= $oPagina->PERMALINK; ?> #slideshow-1 -->
                    <div id="slideshow-2">
                        <ul id="cycle-2" class="cycle-slideshow cycle-obras" data-cycle-slides="> li" data-cycle-timeout="0" data-cycle-prev="#teste1 #slideshow-2 .cycle-prev" data-cycle-next="#teste1 #slideshow-2 .cycle-next" data-cycle-caption="#teste1 #slideshow-2 .custom-caption" data-cycle-fx="carousel" data-cycle-carousel-visible="5" data-allow-wrap="false">
                             <li>
                                 <a href="javascript:void(0);" class="link-imagem">
                                     <img src="/imagem/site/obra-small.jpg"/>
                                 </a>
                             </li>
                            <li>
                                <a href="javascript:void(0);" class="link-imagem">
                                    <img src="/imagem/site/obra-small.jpg"/>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0);" class="link-imagem">
                                    <img src="/imagem/site/obra-small.jpg"/>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0);" class="link-imagem">
                                    <img src="/imagem/site/obra-small.jpg"/>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0);" class="link-imagem">
                                    <img src="/imagem/site/obra-small.jpg"/>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0);" class="link-imagem">
                                    <img src="/imagem/site/obra-small.jpg"/>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0);" class="link-imagem">
                                    <img src="/imagem/site/obra-small.jpg"/>
                                </a>
                            </li>
                        </ul> <!-- #cycle-2 -->

                        <a href="javascript:void(0);" class="cycle-prev"><span class="icon-arrow-left-white"></span></a>
                        <a href="javascript:void(0);" class="cycle-next"><span class="icon-arrow-right-white"></span></a>
                    </div> <!-- # #slideshow-2 -->
                </div> <!-- .page-projeto -->
            </div> <!-- .modal-body -->
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

    <script>
        jQuery(document).ready(function($) {

            var slideshows = $('#teste1 .cycle-slideshow').on('cycle-next cycle-prev', function(e, opts) {
                // advance the other slideshow
                slideshows.not(this).cycle('goto', opts.currSlide);
            });

            $('#teste1 #cycle-2 .cycle-slide').click(function() {
                var index = $('#teste1 #cycle-2').data('cycle.API').getSlideIndex(this);
                slideshows.cycle('goto', index);
            });

            $(".modal-content").css('border', 'none');
        });
    </script>
