<?
echo $this->doctype();
header("Content-Type: text/html; charset=utf-8");
?>
<html>
    <head>
        <title>Área Restrita - Login</title>
        <meta name="language" content="pt-br" />
        <meta http-equiv="imagetoolbar" content="no" />
        <meta http-equiv="Pragma" content="no-cache" />
        <link href="/library/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="/css/login.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="/library/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="/library/jquery-migrate-1.1.1.min.js"></script>
        <script type="text/javascript" src="/library/placeHolder.js"></script>
        <script type="text/javascript" src="/library/jqueryTools/jquery.tools.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $('input[placeholder], textarea[placeholder]').placeholder();
            });
        </script>
    </head>
    <body>
       <?= $this->partial('_includes/mensagem_alerta.phtml','adm') ?>
        <div id="TOPO">
            <div class="bg2"></div>
            <div class="centro">
                <div id="CON_LOGIN" align="center">
                    <h1>Área Administrativa</h1>
                    <div id="FORM">
                        <form id="formLogin" enctype="multipart/form-data" method="post" action="" >
                            <div class="form-group">
                                <label>Login: </label>
                                <input name="LOGIN" id="LOGIN" class="validate[required]"/>
                            </div>
                            <div class="form-group">
                                <label>Senha: </label>
                                <input type="password" name="SENHA" id="SENHA" class="validate[required]"/>
                            </div>
                            <button class="btn btn-default">Entrar</button>
                        </form>
                        <a style="color:#ED1651;margin-top: 10px;display: block;" href="/adm/acl/recuperasenha/">Esqueci minha senha</a>

                    </div>
                </div>
            </div>
        </div>
    </body>
</html>