<div class="extra-bg-dicas">
    <div class="container">
        <div class="box-dicas">
            <div class="cycle-nav"></div>
            <div class="row">
                <div class="col-xs-1">
                    <a href="javascript:void(0);" class="cycle-prev"><span class="sr-only">Anterior</span><img src="/imagem/site/dica-prev.jpg"/></a>
                </div>
                <div class="col-xs-10 dicas-principal">
                    <ul class="cycle-slideshow" data-cycle-fx="scrollHorz" data-cycle-timeout="5000" data-cycle-speed="1800" data-cycle-slides="> li" data-cycle-pager=".box-noticias .cycle-nav" data-cycle-next=".box-noticias .cycle-next" data-cycle-prev=".box-noticias .cycle-prev" data-cycle-easing="easeInOutExpo" data-cycle-log="false">
                        <? foreach ($this->voDica as $oDica) { ?>
                            <li>
                                <div class="media">
                                    <div class="media-body">
                                        <div class="noticia-content">

                                            <div class="col-xs-6">
                                                <p class="point-title"><?=$oDica->TITULO;?></p>
                                                <p class="dica-resumo"><?=$oDica->RESUMO;?></p>
                                                <p class="dica-texto"><?=$oDica->TEXTO;?></p>
                                            </div>
                                            <div class="col-xs-6">
                                                <?=$oDica->getImgDestaque(array(320,201));?>
                                            </div>

                                        </div> <!-- .noticia-content -->

                                    </div> <!-- .media-body -->
                                </div>
                            </li>
                        <? } ?>
                    </ul>
                </div>
                <div class="col-xs-1">
                    <a href="javascript:void(0);" class="cycle-next"><span class="sr-only">Próximo</span><img src="/imagem/site/dica-next.jpg"/></a>
                </div>
            </div>
            </div> <!-- .box-noticias -->
    </div>
</div>