<div id="RODAPE">
    <div class="container">
        <div class="row">
            <div class="col-xs-4">
                <p class="media-heading"><strong>Centrais de Atendimento</strong></p>
                <p>Utilize nosso central de atendimento para falar com um de nossos atendentes.
                    Será um prazer atende-lo.</p>
            </div>
            <div class="col-xs-4">
                <div class="col-xs-6">
                    <ul class="navbar">
                        <li>
                            <a href="/">INICIAL</a>
                        </li>
                        <li>
                            <a href="/empresa">EMPRESA</a>
                        </li>
                        <li>
                            <a href="/servicos">SERVIÇOS</a>
                        </li>
                    </ul>
                </div>
                <div class="col-xs-6">
                    <ul class="navbar">
                        <li>
                            <a href="/obras">OBRAS</a>
                        </li>
                        <li>
                            <a href="/cliente">CLIENTES</a>
                        </li>
                        <li>
                            <a href="/contato">CONTATO</a>
                        </li>
                    </ul>
                </div>
                <div class="col-xs-12 redes-sociais">
                    <ul>
                        <li>
                            <a href="/facebook"><img src="/imagem/site/icon/iconfacebook.png" alt="Facebook"></a>
                        </li>
                        <li>
                            <a href="/twitter"><img src="/imagem/site/icon/icontwitter.png" alt="Twitter"></a>
                        </li>
                        <li>
                            <a href="/instagram"><img src="/imagem/site/icon/iconinstagram.png" alt="Instagram"></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-4">
                <div class="contato-bg">
                    <div class="col-xs-5"></div>
                    <div class="col-xs-7 envie-mensagem">
                        <p>Envie sua <strong>Mensagem</strong></p>
                    </div>
                </div>
                <p class="endereco">R.Curuçá, 734 - Telégrafo - Belém - PA - 66050-080</p>
            </div>
        </div>
    </div>

</div>