<div id="RODAPE">
    <div class="container">
        <div class="row">
            <div class="col-xs-4">
                <p class="media-heading"><strong>Centrais de Atendimento</strong></p>
                <p>Utilize nosso central de atendimento para falar com um de nossos atendentes.
                    Será um prazer atende-lo.</p>
            </div>
            <div class="col-xs-4">
                <div class="col-xs-6">
                    <ul class="navbar">
                        <li class="<?= ZC_Util::isActiveLink('/index/index', array('active')); ?>">
                            <a href="<?= $this->baseUrl('/') ?>">INICIAL</a>
                        </li>
                        <li class="<?= ZC_Util::isActiveRoute('empresa', array('active')); ?>">
                            <a href="<?= $this->baseUrl('/empresa') ?>">EMPRESA</a>
                        </li>
                        <li class="<?= ZC_Util::isActiveRoute('servicos', array('active')); ?>">
                            <a href="<?= $this->baseUrl('/servicos') ?>">SERVIÇOS</a>
                        </li>

                    </ul>
                </div>
                <div class="col-xs-6">
                    <ul class="navbar">
                        <li class="<?= ZC_Util::isActiveRoute('obras', array('active')); ?>">
                            <a href="<?= $this->baseUrl('/obras') ?>">OBRAS</a>
                        </li>
                        <li class="<?= ZC_Util::isActiveRoute('clientes', array('active')); ?>">
                            <a href="<?= $this->baseUrl('/clientes') ?>">CLIENTES</a>
                        </li>
                        <li class="<?= ZC_Util::isActiveRoute('contato', array('active')); ?>">
                            <a href="<?= $this->baseUrl('/contato') ?>">CONTATO</a>
                        </li>
                    </ul>
                </div>
                <div class="col-xs-12 redes-sociais">
                    <ul>
                        <li>
                            <a href="#" target="_blank"><img src="/imagem/site/icon/iconfacebook.png" alt="Facebook"></a>
                        </li>
                        <li>
                            <a href="#" target="_blank"><img src="/imagem/site/icon/icontwitter.png" alt="Twitter"></a>
                        </li>
                        <li>
                            <a href="#" target="_blank"><img src="/imagem/site/icon/iconinstagram.png" alt="Instagram"></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-4">
                <a href="/contato" class="link-mensagem">
                    <div class="contato-bg">
                        <div class="col-xs-5"></div>
                        <div class="col-xs-7 envie-mensagem">
                            <p>Envie sua <strong>Mensagem</strong></p>
                        </div>
                    </div>
                </a>

                <p class="endereco">R.Curuçá, 734 - Telégrafo - Belém - PA - 66050-080</p>
            </div>
        </div>
    </div>

</div>