<div class="col-xs-12">
    <div id="slideshow-galeria">
        <div id="cycle-2" class="cycle-slideshow" data-cycle-fx="carousel" data-cycle-timeout="6000" data-cycle-speed="1800" data-cycle-slides="> div" data-cycle-next="#slideshow-galeria .next" data-cycle-prev="#slideshow-galeria .prev" data-cycle-easing="easeInOutExpo" data-cycle-carousel-visible="3" data-cycle-log="false">
            <? foreach ($this->voObra as $oObra) { ?>
                <div><a href="/obra/<?=$oObra->PERMALINK;?>"><?=$oObra->getImgDestaque(array(231,201));?></a></div>
            <? } ?>
        </div>
        <a class="prev" href="#"><img src="/imagem/site/paginator-left.jpg"/></a>
        <a class="next" href="#"><img src="/imagem/site/paginator-right.jpg"/></a>
    </div>
</div>
<div class="col-xs-9"></div>
<div class="col-xs-3 margin-obras">
    <a href="/obras">Ver todas</a>
</div>