<div class="extra-bg-dicas">
    <div class="container">
        <div class="box-dicas">
            <p class="title-parceiros">MARCAS PARCEIRAS</p>
            <div class="cycle-nav"></div>
            <div class="row">
                <div class="col-xs-1 pager-parceiros">
                    <a href="javascript:void(0);" class="cycle-prev"><span class="sr-only">Anterior</span><img src="/imagem/site/dica-prev.jpg"/></a>
                </div>
                <div class="col-xs-10 dicas-principal">
                    <ul class="cycle-slideshow cycle-parceiros" data-cycle-fx="carousel" data-cycle-timeout="5000" data-cycle-speed="1800" data-cycle-slides="> li" data-cycle-pager=".box-noticias .cycle-nav" data-cycle-carousel-visible="4" data-cycle-next=".row .cycle-next" data-cycle-prev=".row .cycle-prev" data-cycle-easing="easeInOutExpo" data-cycle-log="false">
                        <? foreach ($this->voParceiro as $oParceiro) { ?>
                            <li>
                                <a href="<?=$oParceiro->LINK;?>" target="_blank">
                                    <?=$oParceiro->getImgDestaque(array(179,75));?>
                                </a>
                            </li>
                        <? } ?>
                    </ul>
                </div>
                <div class="col-xs-1 pager-parceiros">
                    <a href="javascript:void(0);" class="cycle-next "><span class="sr-only">Próximo</span><img src="/imagem/site/dica-next.jpg"/></a>
                </div>
            </div>
        </div> <!-- .box-noticias -->
    </div>
</div>