<?
$bAcl = new ZC_Acl();
$controller = 'pagina';
$pagina = $this->data['action'];
($pagina == 'index') ? $pagina = '' : $pagina;
$paginaInstitucional = $this->page;
$form = $this->form;
?>
<script type="text/javascript">
    $(function() {
        $(".jLock").click(function() {
            var $this = $(this);
            $.post($(this).attr("href"), {ajax: 1}, function(data) {
                if (data.success) {
                    if ($this.is('.bt_lock_on')) {
                        $this.removeClass('bt_lock_on').addClass('bt_lock_off');
                    } else {
                        $this.removeClass('bt_lock_off').addClass('bt_lock_on');
                    }
                }
            }, 'json');
            return false;
        });
        $(".jDestaqueOrdem").keyup(function() {
            if ($(this).val() != 0) {
                $.post("/adm/<?= $controller ?>/adddestaqueordem/ajax/true/", {ID: $(this).attr('rel'), VALOR: $(this).val()}, function(json) {
                    var v1 = json.valorAntigo - 1;
                    var v2 = json.valor - 1;

                    var contentAntigo = $(".padrao tbody tr td .jDestaqueOrdem[value='" + json.valorAntigo + "']");
                    var contentNovo = $(".padrao tbody tr td .jDestaqueOrdem[value='" + json.valor + "']");

                    var aux = contentAntigo;
                    contentAntigo.attr("value", json.valor);
                    contentNovo.attr("value", json.valorAntigo);
                }, "json");
            }

        });

        $(".jDestaque").click(function() {
            var valor = $(this).val();
            if ($(this).is(".ativo")) {
                $(this).removeClass("ativo");
                $(this).next().addClass("hide");
                var status = 0;
                $(this).next().val('0');
                $.post("/adm/<?= $controller ?>/adddestaqueordem/ajax/true/", {ID: valor, VALOR: 0}, function() {

                }, "json");
            } else {
                var status = 1;
                $(this).addClass("ativo");
                $(this).next().removeClass("hide");
            }
            $.post("/adm/<?= $controller ?>/adddestaque/ajax/true/ID/" + valor + "/S/" + status, "", function() {

            }, "json");
        });
    })
</script>
<style type="text/css">
    .jDestaque{display: inline-block;}
    .jDestaqueOrdem{width: 20px;text-align: center;}
    .hide{display: none;}
    select{
        padding: 7.3px;
        background: none repeat scroll 0 0 #F2E4D8;
        border: 1px solid #C7B3A6;
        color: #4A4A4A;
        cursor: pointer;
        display: inline-block;
    }
    select:hover{
        background: #D7C0AE;
    }
</style>
<h1><?= $this->title; ?></h1>
<form action="/adm/pagina/excluir" method="post">
    <? if ($bAcl->verifica(false, 'adm', $controller, 'inserealtera' . $pagina. "/{$paginaInstitucional}")): ?>
        <? if ($pagina == 'institucional'){ ?>
            <a class="button jInfo" href="<?= $this->baseUrl("/adm/inserealtera{$pagina}/{$paginaInstitucional}/{$form}"); ?>" title="Cadastrar">Cadastrar</a>
        <? }else{?>
            <a class="button jInfo" href="<?= $this->baseUrl("/adm/{$controller}/inserealtera/{$pagina}"); ?>" title="Cadastrar">Cadastrar</a>
        <? } ?>
    <? endif; ?>

    <? if (count($this->vo)): ?>

        <p><?= $this->vo->getTotalItemCount() ?> registro(s) encontrados.</p>
        <table class="padrao table table-bordered">
            <thead>
                <tr>
                    <? if ($this->destaque) { ?>
                        <th width="60" style="text-align: center;"><img src="/imagem/icone/star.png" alt="destaque" title="Destaque?" /></th>
                    <? } ?>
                    <? if ($this->elementosColuna) { ?>
                        <? foreach ($this->elementosColuna as $title => $name) { ?>
                            <th><?=$title;?></th>
                        <? } ?>
                    <? }else{ ?>
                        <th>TÍTULO</th>
                        <th>RESUMO</th>
                    <? } ?>
                    <th width="160">AÇÕES</th>
                </tr>
            </thead>
            <tbody>
                <? foreach ($this->vo as $o): ?>
                    <tr>
                        <? if ($this->destaque) { ?>
                            <td>
                                <input class="jDestaque <?= $o->FL_DESTAQUE == 1 ? "ativo" : "" ?>" <?= $o->FL_DESTAQUE == 1 ? "checked" : "" ?> name="ID_DESTAQUE" type="checkbox" value="<?= $o->ID ?>" />
                                <input class="jDestaqueOrdem <?= $o->FL_DESTAQUE == 1 ? "" : "hide" ?>" rel="<?= $o->ID ?>" name="DESTAQUE_ORDEM" type="text" value="<?= $o->FL_DESTAQUE_ORDEM ?>" />
                            </td>
                        <? } ?>

                        <? if ($this->elementosColuna) { ?>
                            <? foreach ($this->elementosColuna as $title => $name) { ?>
                                <td><?=$o->$name;?></td>
                            <? } ?>
                        <? }else{ ?>
                            <td><?=$o->TITULO;?></td>
                            <td><?=$o->RESUMO;?></td>
                        <? } ?>
                        <td class="action">
                            <div style="text-align:left">
                                <? if ($this->subpagina): ?>
                                    <a title="adicionar subpágina" href="<?= $this->baseUrl("/adm/{$controller}/inserealtera{$pagina}/pagina/{$paginaInstitucional}/ID_PAI/" . $o->ID) ?>"><span class="glyphicon glyphicon-plus"></span></a>
                                <? endif; ?>

                                <a title="editar página" href="<?= $this->baseUrl("/adm/{$controller}/inserealtera{$pagina}/pagina/{$paginaInstitucional}/ID/" . $o->ID) ?>"><span class="glyphicon glyphicon-pencil"></span></a>

                                <? if (Zend_Registry::get("oUsuario")->ID_GRUPO == 1 || $o->FL_LOCK == 0): ?>
                                    <a title="excluir página" href="<?= $this->baseUrl("/adm/{$controller}/excluir/move/{$pagina}/pagina/{$paginaInstitucional}/ID/" . $o->ID) ?>"><span class="glyphicon glyphicon-trash"></span></a>
                                <? endif; ?>
                            </div>
                        </td>
                    </tr>
                    <? if ($this->subpagina): ?>
                        <? if ($voFilho = $o->getFilho()): ?>
                            <? foreach ($voFilho as $oFilho): ?>
                                <tr class="subpage">
                                    <td>&rdsh; <input name="ID[]" type="checkbox" value="<?= $oFilho->ID ?>" /></td>
                                    <td><?= ($oFilho->IMG_DESTAQUE) ? $oFilho->getImgDestaque(array(60, 40)) : '' ?></td>
                                    <td><?= $oFilho->TITULO;?></td>
                                    <td><?= $oFilho->RESUMO;?></td>
                                    <td class="action">
                                        <a class="bt bt_editar" title="editar página" href="<?= $this->baseUrl("/adm/{$controller}/inserealtera{$pagina}/pagina/{$paginaInstitucional}/ID/" . $oFilho->ID). '/ID_PAI/'.$o->ID ?>"></a>
                                        <a class="bt bt_excluir" title="excluir página" href="<?= $this->baseUrl("/adm/{$controller}/excluir/move/{$pagina}/pagina/{$paginaInstitucional}/ID/" . $oFilho->ID). '/ID_PAI/'.$o->ID ?>"></a>
                                    </td>
                                </tr>
                            <? endforeach; ?>
                        <? endif; ?>
                    <? endif; ?>
                <? endforeach; ?>
            </tbody>
        </table>
        <?= $this->paginationControl($this->vo, 'Sliding', '_includes/paginacao.phtml') ?>
    <? else: ?>
        <p>Nenhum registro encontrado</p>
    <? endif ?>
</form>